// Build-time data access. Single source of truth is resources/ (generated by
// scripts/extract/*). These imports inline the JSON into the static build.
import itemBank from '../../resources/item-bank/item_bank.json';
import translations from '../../resources/translations/short_module_translations.json';
import responseScales from '../../resources/translations/response_scales.json';
import feedback from '../../resources/feedback/feedback_logic.json';

export type Version = 'long' | 'short' | 'ultra_brief';

export interface BankItem {
  section: string;
  scale: string;
  domain_label: string | null;
  item_text: string;
  waves: Record<'S1' | 'S2' | 'S3' | 'S4' | 'S5', string | null>;
  versions: Version[];
  short_module_code: string | null;
  fimi: { origin: string; short_fimi: boolean } | null;
}

export const bank = itemBank as unknown as {
  _meta: any;
  items: BankItem[];
};

export const trans = translations as unknown as {
  _meta: {
    languages: { code: string; name: string; primary: boolean }[];
    n_items: number;
  };
  items: {
    item_code: string;
    construct: string;
    construct_label: string;
    origin: string | null;
    english_harmonised: string;
    english_deployed: string;
    qsf_question: string;
    qsf_choice_id: string | null;
    translations: Record<string, string>;
  }[];
};

export const scales = responseScales as unknown as Record<
  string,
  { language: string; likert_agreement: Record<string, string>; fimi_detection: Record<string, string> }
>;

export const fb = feedback as unknown as {
  _meta: any;
  algorithm: { summary: string; steps: string[]; groups: Record<string, string>; note: string };
  ranking_js: string;
  intro: { lt: string; en: string };
  domains: {
    key: string;
    disinformeter_domain: string;
    subscale_field: string;
    show_flag: string;
    messages: { low: { lt: string; en: string }; high: { lt: string; en: string } };
  }[];
  closing: { lt: string; en: string };
};

// ---- derived helpers ----
// The four affective pathways = D5.3's "four specific dimensions". The General
// Anchor is deliberately NOT a fifth one: it samples across all four and is
// read as a separate cross-cutting overall index (D5.3 §3.1 / Annex A.4).
export const PATHWAYS = [
  { key: 'Threat', label: 'Threat', cssVar: '--d-threat',
    blurb: 'Perceived threat to national identity, security, culture, sovereignty, or social order.' },
  { key: 'Betrayal / Abandonment', label: 'Betrayal / Abandonment', cssVar: '--d-aband',
    blurb: 'Perceived failure of institutions, allies, or mainstream media to protect citizens.' },
  { key: 'Fear / Pragmatism', label: 'Fear / Pragmatism', cssVar: '--d-fear',
    blurb: 'Anxiety-driven openness to accommodation with hostile or rival powers as a route to safety.' },
  { key: 'Foreign-Power Admiration', label: 'Foreign-Power Admiration', cssVar: '--d-admire',
    blurb: 'Positive affect toward Russia, China, or alternative geopolitical models.' },
];

export const GENERAL = {
  key: 'General Anchor', label: 'General Anchor', cssVar: '--d-general',
  blurb: 'A short cross-cutting set that samples all four pathways. Read as one overall index of ' +
    'receptivity, reported beside the profile, never as a fifth pathway.',
};

export const STUDIES = [
  { id: 'S1', where: 'Lithuania', when: 'Dec 2024', n: 681, role: 'Item-pool generation and scale construction' },
  { id: 'S2', where: 'Lithuania', when: 'Mar 2025', n: 582, role: 'Model refinement; first full 8-item FIMI battery' },
  { id: 'S3', where: 'Germany', when: 'May 2025', n: 782, role: 'Cross-national replication' },
  { id: 'S4', where: '13 countries', when: 'Dec 2025', n: 7783, role: 'Multinational deployment, country profiles, source variants, invariance' },
  { id: 'S5', where: 'Lithuania', when: 'Mar–Apr 2026', n: 248, role: 'External validation + personalized-feedback intervention' },
];

export function countByVersion(v: Version): number {
  return bank.items.filter((i) => i.versions.includes(v)).length;
}

// ---- demonstrator survey content (EN + LT, the two languages with full
//      end-to-end parity: items, feedback, and choice task all exist in both) ----
type Bi = { EN: string; LT: string };
const transByCode: Record<string, (typeof trans.items)[number]> = {};
for (const it of trans.items) transByCode[it.item_code] = it;

function itemText(code: string): Bi {
  const it = transByCode[code];
  return { EN: it?.translations.EN ?? '', LT: it?.translations.LT ?? '' };
}

// Fixed neutral presentation order for the 19 receptivity items: domains are
// interleaved (not grouped or labelled during administration, to avoid cueing
// the construct) and split across two pages. Codes map to scoring domains in
// disinformeter-score.mjs. The 8 FIMI headline-rating items are intentionally
// NOT administered here — FIMI detection is covered behaviourally by the choice
// task at the end of the demonstrator.
const AGREEMENT_ORDER: string[][] = [
  ['th6', 'ab2', 'pa1', 'fch1', 'gen1', 'th9', 'ab4', 'pa2', 'fru1', 'gen2'],
  ['ab7', 'pa4', 'fch2', 'gen5', 'fru2', 'fch3', 'gen7', 'fru3', 'gen3'],
];

export const SURVEY = {
  agreementPages: AGREEMENT_ORDER.map((pg) => pg.map((code) => ({ code, text: itemText(code) }))),
  // Endpoint anchors for the agreement response scale, in both languages.
  scales: { EN: scales.EN, LT: scales.LT },
};
